name: ⭐️ Add Org
description: Add a new organization or community to the list.
title: '<Org Name>'
labels: ["add org"]

body:
  - type: markdown
    attributes:
      value: |
        Before getting started, make sure you have checked the list and that the org does not exist.
        If you want to update an existing org, use "Update Org".

        Only **Region**, **Name**, **City** fields are required.
        All other fields are optional, but would be better if you provide them.

  - type: input
    id: region
    attributes:
      label: Region Code
      description: |
        The region code used to group your organization/community.
        Please choose the appropriate one according to your country or region.
        * [Currently Collected Regions](https://swing.kids/submit)
        * If you cannot find the corresponding one, use "Add Region" or email directly to dev+swing@kjuly.com.
      placeholder: e.g., cn
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Name
      placeholder: e.g., X Studio
    validations:
      required: true

  - type: input
    id: name_local
    attributes:
      label: Local Name
      placeholder: e.g., 某某工作室

  - type: input
    id: since
    attributes:
      label: Year Established
      placeholder: e.g., 2014

  - type: input
    id: city
    attributes:
      label: City
      placeholder: e.g., Xiamen
    validations:
      required: true

  - type: input
    id: province
    attributes:
      label: Province or State
      description: Leave it blank or use the same City value if none is available.
      placeholder: e.g., Fujian

  - type: dropdown
    id: styles
    attributes:
      label: Specific Dance Style
      multiple: false
      default: 0
      options:
        - ANY
        - Balboa
        - Blues
        - Boogie Woogie
        - Shag
  
  - type: input
    id: party
    attributes:
      label: Weekly Party
      description: |
        D: 0 ~ 6 (Sunday to Saturday)
        HH:MM: 00:00 ~ 23:59 (24:00 is also OK)
        e.g.
        `5-20:00`: Every Friday 20:00
        `0-20:00~24:00`: Every Sunday 20:00 ~ 24:00
        `3-20:00~23:00,6-20:00~24:00`: Every Wednesday 20:00 ~ 23:00, Every Saturday 20:00 ~ 24:00
      placeholder: D-HH:MM

  - type: textarea
    id: venue
    attributes:
      label: Venue
      description: The address of the studio or ballroom.
      placeholder: |
        e.g. 
        B203, Zhuzong Building, No.25, East Third Ring Road, Beijing.
        北京市东三环中路25号住总大厦 B203。

  - type: input
    id: email
    attributes:
      label: Email
      placeholder: e.g., abc@eample.com

  - type: input
    id: website
    attributes:
      label: Website or Homepage
      placeholder: e.g., https://example.com

  - type: markdown
    attributes:
      value: |
        Here are some optional fields for social network accounts that may be
        helpful in letting others know more about your organization/community.
        
        Please add the **User ID Only**, not the full URL link.
        For example, if the full URL is https://www.instagram.com/abc, add abc.
  
  - type: input
    id: fb
    attributes:
      label: Facebook
      placeholder: e.g., abc

  - type: input
    id: ig
    attributes:
      label: Instagram
      placeholder: e.g., abc

  - type: input
    id: yt
    attributes:
      label: YouTube
      placeholder: e.g., abc

  - type: input
    id: wo
    attributes:
      label: WeChat Official Account
      placeholder: e.g., abc

  - type: input
    id: bl
    attributes:
      label: Bilibili
      placeholder: e.g., abc

  - type: input
    id: rb
    attributes:
      label: Xiaohongshu
      placeholder: e.g., abc

  - type: textarea
    id: notes
    attributes:
      label: Notes
      placeholder: You can add any additional instructions or tips for dancers here if needed.
