blank_issues_enabled: false
contact_links:
  - name: ⛄️ Others
    url: https://github.com/swingdance/.github/blob/main/SUPPORT.md
    about: If you have any other questions or suggestions, email directly to dev+swing@kjuly.com.

