name: Check Closed Issue

on:
  issues:
    types: [closed]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  check-closed-issue-to-close-pr:
    if: contains(github.event.issue.labels.*.name, 'add org') || contains(github.event.issue.labels.*.name, 'update org')
    runs-on: ubuntu-latest
    steps:
      - name: Close PR from Issue
        uses: swingdance/close-pr-from-issue@main
        with:
          token: "${{ secrets.GH_TOKEN }}"
