name: Check Opened Issue

on:
  issues:
    types: [opened, reopened]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  check-opened-issue-to-add-org:
    if: contains(github.event.issue.labels.*.name, 'add org')
    uses: swingdance/entity-ci/.github/workflows/create_pr_to_add_entity.yml@main
    with:
      type: org
      template_filename: 02-add_entity.yml
      reusable_workflow_repo: swingdance/entity-ci
    secrets:
      token: "${{ secrets.GH_TOKEN }}"

  check-opened-issue-to-update-org:
    if: contains(github.event.issue.labels.*.name, 'update org')
    uses: swingdance/entity-ci/.github/workflows/create_pr_to_update_entity.yml@main
    with:
      type: org
      template_filename: 03-update_entity.yml
      reusable_workflow_repo: swingdance/entity-ci
    secrets:
      token: "${{ secrets.GH_TOKEN }}"
